### ISSUE TITLE
Basic Navigation System

### ISSUE THREAD

**Issue by BrokenHourGlass** [BrokenHourGlass/Sea_of_Monsters#15]
Create a navigation system that allows players to plot a course on a map and follow it in the game world. This should include an interface for the map and the logic to move the ship along the chosen path.

**Comment by BrokenHourGlass** [comment]
alright, this ones fairly complicated and assumes that a number of features are working and present so lets break this down into sub-issues.

## Sub-issues
- [x] Implement Camera Tracking
- [x] create a test world map
- [ ] create a Map Interface
- [ ] set up plotting a course on the map
- [ ] set system in place to sync world map and Game World
- [ ] do rigorous testing to ensure this feature works
